# Generated by Django 3.0.5 on 2021-11-06 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_request_need_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=300, null=True)),
                ('expiry_date', models.DateField(max_length=50, null=True)),
                ('Quantity', models.IntegerField(null=True)),
                ('members', models.IntegerField(null=True)),
                ('status', models.CharField(default=0, max_length=100)),
                ('benefactor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.Benefactorr')),
            ],
        ),
    ]
