# Generated by Django 3.0.5 on 2021-11-06 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_product_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_add',
            name='Quantity',
        ),
    ]
