# Generated by Django 3.0.5 on 2021-11-06 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_remove_product_add_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_add',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.volunteer_reg'),
        ),
    ]
