# Generated by Django 3.0.5 on 2021-11-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_product_add_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_add',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='product_add',
            name='location',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
