# Generated by Django 3.0.5 on 2021-11-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_remove_benefactorr_h_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefactorr',
            name='city',
        ),
    ]
