# Generated by Django 3.0.5 on 2021-11-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0012_auto_20211111_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefactorr',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='volunteer_reg',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
