# Generated by Django 3.0.5 on 2021-11-16 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0013_auto_20211111_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_need',
            name='need_status',
            field=models.CharField(default='apply', max_length=100),
        ),
        migrations.AddField(
            model_name='request_need',
            name='status1',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='request_need',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.volunteer_reg'),
        ),
    ]
