# Generated by Django 3.0.5 on 2021-11-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0016_auto_20211120_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_add',
            name='status1',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
