# Generated by Django 3.0.5 on 2021-11-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0017_product_add_status1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefactorr',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
